### ISSUE TITLE
Funktion um je ein Modul auszulesen und das in ein json zu schreiben

### ISSUE THREAD

**Issue by Hezel2000** [Hezel2000/modulhandbuch#1]
Die Funktion soll folgendes tun:
Es soll aus der Gesamtdatei immer nur ein Modul ausgelesen werden, und anschließend als eine .json Datei mit dem entsprechenden Dateinamen abgespeichert werden.

**Comment by LDietel** [comment]
Ok, das Programm geht, ich habe es als Issue1 hochgeladen
